// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC73okrXOcXX-Pp-Oz9r5iRPxh6-kPRWow',
    appId: '1:201983642705:web:70d464d319ea354f70bc70',
    messagingSenderId: '201983642705',
    projectId: 'library-1c4f8',
    authDomain: 'library-1c4f8.firebaseapp.com',
    storageBucket: 'library-1c4f8.appspot.com',
    measurementId: 'G-DDK1B303FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrzNT-6vcqsmC6Ppjs1BhjBXObmnx_W_Y',
    appId: '1:201983642705:android:ef544a91e75cb35a70bc70',
    messagingSenderId: '201983642705',
    projectId: 'library-1c4f8',
    storageBucket: 'library-1c4f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ypxeANS8zdUW2VQXIDghjgYMMOaVozY',
    appId: '1:201983642705:ios:11e086e4bc1ea33070bc70',
    messagingSenderId: '201983642705',
    projectId: 'library-1c4f8',
    storageBucket: 'library-1c4f8.appspot.com',
    iosClientId: '201983642705-9s5kujkspf8ebmpjf19rr27ql3e1itbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.librarry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ypxeANS8zdUW2VQXIDghjgYMMOaVozY',
    appId: '1:201983642705:ios:11e086e4bc1ea33070bc70',
    messagingSenderId: '201983642705',
    projectId: 'library-1c4f8',
    storageBucket: 'library-1c4f8.appspot.com',
    iosClientId: '201983642705-9s5kujkspf8ebmpjf19rr27ql3e1itbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.librarry',
  );
}
